// <auto-generated />
using System;
using Fast_C__Pizza_Co_Back_End.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fast_C__Pizza_Co_Back_End.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230831231449_AddPizzaData")]
    partial class AddPizzaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaDataUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("SoldOut")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PizzaData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ingredients = "Bread with italian olive oil and rosemary",
                            Name = "Focaccia",
                            PhotoName = "pizzas/focaccia.jpg",
                            Price = 6,
                            Quantity = 0,
                            SoldOut = false
                        },
                        new
                        {
                            Id = 2,
                            Ingredients = "Tomato, basil and mozarella",
                            Name = "Pizza Margherita",
                            PhotoName = "pizzas/margherita.jpg",
                            Price = 10,
                            Quantity = 0,
                            SoldOut = false
                        },
                        new
                        {
                            Id = 3,
                            Ingredients = "Tomato, mozarella, spinach, and ricotta cheese",
                            Name = "Pizza Spinaci",
                            PhotoName = "pizzas/spinaci.jpg",
                            Price = 12,
                            Quantity = 0,
                            SoldOut = false
                        },
                        new
                        {
                            Id = 4,
                            Ingredients = "Tomato, mozarella, mushrooms, and onion",
                            Name = "Pizza Funghi",
                            PhotoName = "pizzas/funghi.jpg",
                            Price = 13,
                            Quantity = 0,
                            SoldOut = false
                        },
                        new
                        {
                            Id = 6,
                            Ingredients = "Tomato, mozarella, mushrooms, and onion",
                            Name = "Pizza Salamino",
                            PhotoName = "pizzas/funghi.jpg",
                            Price = 15,
                            Quantity = 0,
                            SoldOut = true
                        },
                        new
                        {
                            Id = 5,
                            Ingredients = "Tomato, mozarella, ham, aragula, and burrata cheese",
                            Name = "Pizza Prosciutto",
                            PhotoName = "pizzas/prosciutto.jpg",
                            Price = 18,
                            Quantity = 0,
                            SoldOut = false
                        });
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaObj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzaOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaOrderId");

                    b.ToTable("PizzaObj");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Focaccia",
                            PizzaOrderId = 1,
                            Price = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza Spinaci",
                            PizzaOrderId = 1,
                            Price = 12,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PizzaOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryTime = new DateTime(2023, 9, 1, 11, 14, 48, 920, DateTimeKind.Local).AddTicks(3005),
                            TotalCost = 36,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaObj", b =>
                {
                    b.HasOne("Fast_C__Pizza_Co_Back_End.Models.PizzaOrder", "PizzaOrder")
                        .WithMany("PizzaArr")
                        .HasForeignKey("PizzaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PizzaOrder");
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaOrder", b =>
                {
                    b.Navigation("PizzaArr");
                });
#pragma warning restore 612, 618
        }
    }
}
