// <auto-generated />
using System;
using Fast_C__Pizza_Co_Back_End.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fast_C__Pizza_Co_Back_End.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230823042032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaObj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzaOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaOrderId");

                    b.ToTable("PizzaObj");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Focaccia",
                            PizzaOrderId = 1,
                            Price = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza Spinaci",
                            PizzaOrderId = 1,
                            Price = 12,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PizzaOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryTime = new DateTime(2023, 8, 23, 16, 20, 32, 242, DateTimeKind.Local).AddTicks(2999),
                            TotalCost = 36,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaObj", b =>
                {
                    b.HasOne("Fast_C__Pizza_Co_Back_End.Models.PizzaOrder", "PizzaOrder")
                        .WithMany("PizzaArr")
                        .HasForeignKey("PizzaOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PizzaOrder");
                });

            modelBuilder.Entity("Fast_C__Pizza_Co_Back_End.Models.PizzaOrder", b =>
                {
                    b.Navigation("PizzaArr");
                });
#pragma warning restore 612, 618
        }
    }
}
